target-version = "py311"
line-length = 100

[lint]
select = ["E", "F", "W", "I", "UP"]
ignore = [
    "E501",   # line too long
    "F401",   # unused import (faux positifs __init__.py)
    "UP007",  # X | Y union syntax
    "UP006",  # use `type` instead of `Type`
    "UP035",  # deprecated typing imports
]
exclude = ["notebooks/", ".venv/", "build/"]

[lint.isort]
known-first-party = ["src"]

[lint.per-file-ignores]
"tests/*" = ["F811"]
